#
# RcppExports.R
# This file is part of hashtable
#
# Copyright (C) 2013 - Giacomo Bergami
#
# hashtable is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# hashtable is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with hashtable. If not, see <http://www.gnu.org/licenses/>.
#


# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getPtr <- function(g) {
    .Call('hashtable_getPtr', PACKAGE = 'hashtable', g)
}

ptr_ToObj <- function(g) {
    .Call('hashtable_ptr_ToObj', PACKAGE = 'hashtable', g)
}

rmHashtable <- function(xp) {
    .Call('hashtable_rmHashtable', PACKAGE = 'hashtable', xp)
}

newHashT <- function() {
    .Call('hashtable_newHashT', PACKAGE = 'hashtable')
}

getHMaxId <- function(xp) {
    .Call('hashtable_getHMaxId', PACKAGE = 'hashtable', xp)
}

getHSize <- function(xp) {
    .Call('hashtable_getHSize', PACKAGE = 'hashtable', xp)
}

idToObj <- function(xp, id) {
    .Call('hashtable_idToObj', PACKAGE = 'hashtable', xp, id)
}

addKeyValueElem <- function(xp, key, val) {
    .Call('hashtable_addKeyValueElem', PACKAGE = 'hashtable', xp, key, val)
}

hasKeyValueElem <- function(xp, key, val) {
    .Call('hashtable_hasKeyValueElem', PACKAGE = 'hashtable', xp, key, val)
}

remKeyValueElem <- function(xp, key, val) {
    .Call('hashtable_remKeyValueElem', PACKAGE = 'hashtable', xp, key, val)
}

rmMap <- function(xp) {
    .Call('hashtable_rmMap', PACKAGE = 'hashtable', xp)
}

newMap <- function() {
    .Call('hashtable_newMap', PACKAGE = 'hashtable')
}

map_AddKeyVal <- function(m, k, val) {
    .Call('hashtable_map_AddKeyVal', PACKAGE = 'hashtable', m, k, val)
}

map_hasKey <- function(m, k) {
    .Call('hashtable_map_hasKey', PACKAGE = 'hashtable', m, k)
}

map_getVal <- function(m, k) {
    .Call('hashtable_map_getVal', PACKAGE = 'hashtable', m, k)
}

