# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getPtr <- function(g) {
    .Call('hashtable_getPtr', PACKAGE = 'hashtable', g)
}

ptr_ToObj <- function(g) {
    .Call('hashtable_ptr_ToObj', PACKAGE = 'hashtable', g)
}

rmHashtable <- function(xp) {
    .Call('hashtable_rmHashtable', PACKAGE = 'hashtable', xp)
}

newHashT <- function() {
    .Call('hashtable_newHashT', PACKAGE = 'hashtable')
}

getHMaxId <- function(xp) {
    .Call('hashtable_getHMaxId', PACKAGE = 'hashtable', xp)
}

getHSize <- function(xp) {
    .Call('hashtable_getHSize', PACKAGE = 'hashtable', xp)
}

idToObj <- function(xp, id) {
    .Call('hashtable_idToObj', PACKAGE = 'hashtable', xp, id)
}

addKeyValueElem <- function(xp, key, val) {
    .Call('hashtable_addKeyValueElem', PACKAGE = 'hashtable', xp, key, val)
}

hasKeyValueElem <- function(xp, key, val) {
    .Call('hashtable_hasKeyValueElem', PACKAGE = 'hashtable', xp, key, val)
}

remKeyValueElem <- function(xp, key, val) {
    .Call('hashtable_remKeyValueElem', PACKAGE = 'hashtable', xp, key, val)
}

rmMap <- function(xp) {
    .Call('hashtable_rmMap', PACKAGE = 'hashtable', xp)
}

newMap <- function() {
    .Call('hashtable_newMap', PACKAGE = 'hashtable')
}

map_AddKeyVal <- function(m, k, val) {
    .Call('hashtable_map_AddKeyVal', PACKAGE = 'hashtable', m, k, val)
}

map_hasKey <- function(m, k) {
    .Call('hashtable_map_hasKey', PACKAGE = 'hashtable', m, k)
}

map_getVal <- function(m, k) {
    .Call('hashtable_map_getVal', PACKAGE = 'hashtable', m, k)
}

